target-version = "py312"
line-length = 100
preview = true
extend-exclude = ["c2rust"]

[lint]
select = ["E", "W", "F", "RUF", "TRY", "PLC", "PLE", "PLW06",
          "UP024", "UP018", "UP012", "UP006", "PLW15"]
ignore = ["E305", "E302", "E731", "E111", "E114", "E117", "E501",
          "TRY003", "RUF010", "PLC1901"]


