#!/usr/bin/env python3

from pathlib import Path
import sys
import os

if __name__ == "__main__":
    tenjdir = Path(sys.argv[0]).resolve().parent
    rootdir = tenjdir.parent
    localuv = Path(rootdir, "_local", "uv")
    localcg = Path(rootdir, "_local", "uv.toml")

    if localuv.exists() and localcg.exists():
        args = ["uv", "run", "--project", tenjdir, "--config-file", localcg, "cli/main.py"]
        os.execv(str(localuv), args + sys.argv[1:])
    else:
        print("Before running 10j, please run     sh 10j/sh/provision.sh", file=sys.stderr)
        sys.exit(1)
