name: not-rocket-science

on:
  push:
    branches: [ "test/**" ]
  pull_request:
    branches: [ "main" ]

jobs:
  not-rocket-science-checks:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Provision uv
        run: sh cli/_provision.sh

      - name: Health check
        run: cli/10j status

      - name: Code linting and formatting checks
        run: cli/10j check-star

      - name: Ensure no large files were accidentally added
        run: cli/10j check-repo-file-sizes
