name: not-rocket-science

on:
  push:
    branches: [ "test/**" ]
  pull_request:
    branches: [ "main" ]

jobs:
  not-rocket-science-checks:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - uses: brk/setup-ocaml-unsandboxed@89ccd7e026e5aa5244af063742f11cf633a6c0e1 # v3.3.0
        with:
          ocaml-compiler: 5
          # Allow the chosen version of OCaml to float, even if the usual provisioning
          # process would pin it.

      - name: Provision dependencies
        run: sh cli/sh/provision.sh

      - name: Health check
        run: cli/10j status

      - name: Code linting and formatting checks
        run: cli/10j check-star

      - name: Ensure no large files were accidentally added
        run: cli/10j check-repo-file-sizes
